## Artificial Neural Networks - Forward Propagation ##

Let's start by randomly initializing the weights and the biases in the network. We have 6 weights and 3 biases, one for each node in the hidden layer as well as for each node in the output layer.

In [1]:
import numpy as np # import Numpy library to generate 

weights = np.around(np.random.uniform(size=6), decimals=2) # initialize the weights
biases = np.around(np.random.uniform(size=3), decimals=2) # initialize the biases

In [2]:
print(weights)
print(biases)

[0.7  0.41 0.02 0.9  0.24 0.07]
[0.34 0.29 0.41]


In [3]:
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

In [4]:
z_11 = x_1 * weights[0] + x_2 * weights[1] + biases[0]

print('The weighted sum of the inputs at the first node in the hidden layer is {}'.format(z_11))

The weighted sum of the inputs at the first node in the hidden layer is 1.0385


Next, let's compute the weighted sum of the inputs, at the second node of the hidden layer. Assign the value to z_12.

In [5]:
z_12 = x_1 * weights[2] + x_2 * weights[3] + biases[1]
z_12

1.065

In [6]:
print('The weighted sum of the inputs at the second node in the hidden layer is {}'.format(np.around(z_12, decimals=4)))

The weighted sum of the inputs at the second node in the hidden layer is 1.065


In [7]:
a_11 = 1.0 / (1.0 + np.exp(-z_11))

print('The activation of the first node in the hidden layer is {}'.format(np.around(a_11, decimals=4)))

The activation of the first node in the hidden layer is 0.7386


In [9]:
a_12 = 1.0 / (1.0 + np.exp(-z_12))
print('The activation of the second node in the hidden layer is {}'.format(np.around(a_12, decimals=4)))

The activation of the second node in the hidden layer is 0.7436


In [10]:
z_2 = a_11 * weights[4] + a_12 * weights[5] + biases[2]
print('The weighted sum of the inputs at the node in the output layer is {}'.format(np.around(z_2, decimals=4)))

The weighted sum of the inputs at the node in the output layer is 0.6393


In [11]:
a_2 = 1.0 / (1.0 + np.exp(-z_2))
print('The output of the network for x1 = 0.5 and x2 = 0.85 is {}'.format(np.around(a_2, decimals=4)))

The output of the network for x1 = 0.5 and x2 = 0.85 is 0.6546


## Initialize a Network ##

In [12]:
n = 2 # number of inputs
num_hidden_layers = 2 # number of hidden layers
m = [2, 2] # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer

In [13]:
import numpy as np # import the Numpy library

num_nodes_previous = n # number of nodes in the previous layer

network = {} # initialize network an an empty dictionary

# loop through each layer and randomly initialize the weights and biases associated with each node
# notice how we are adding 1 to the number of hidden layers in order to include the output layer
for layer in range(num_hidden_layers + 1): 
    
    # determine name of layer
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
    
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network

{'layer_1': {'node_1': {'weights': array([0.02, 0.39]), 'bias': array([0.76])}, 'node_2': {'weights': array([0.58, 0.44]), 'bias': array([0.07])}}, 'layer_2': {'node_1': {'weights': array([0.93, 0.55]), 'bias': array([0.17])}, 'node_2': {'weights': array([0.33, 0.23]), 'bias': array([0.92])}}, 'output': {'node_1': {'weights': array([0.42, 0.72]), 'bias': array([0.21])}}}


In [16]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [17]:
small_network = initialize_network(5, 3, [3, 2, 3], 1)

## Compute Weighted Sum at Each Node ##

In [18]:
def compute_weighted_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

In [19]:
from random import seed
import numpy as np

np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


In [20]:
node_weight = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']

weighted_sum = compute_weighted_sum(inputs, node_weight, node_bias)
weighted_sum

array([1.5146])

### Compute Node Activation ##

In [21]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

In [22]:
output = node_activation(weighted_sum)
output

array([0.81974193])

## Forward Propagation ##

In [23]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [24]:
small_network_predictions = forward_propagate(small_network, inputs)
print('Small network predictions : {}'.format(np.around(small_network_predictions[0])))

The outputs of the nodes in hidden layer number 1 is [0.8197, 0.6283, 0.8364]
The outputs of the nodes in hidden layer number 2 is [0.8275, 0.8147]
The outputs of the nodes in hidden layer number 3 is [0.7389, 0.6879, 0.5867]
Small network predictions : 1.0


In [25]:
my_network = initialize_network(5, 3, [2, 3, 2], 3)

In [26]:
inputs = np.around(np.random.uniform(size=5), decimals=2)

In [27]:
predictions = forward_propagate(my_network, inputs)
print('The predicted values by the network for the given input are {}'.format(predictions))

The outputs of the nodes in hidden layer number 1 is [0.8857, 0.8889]
The outputs of the nodes in hidden layer number 2 is [0.7822, 0.6965, 0.7411]
The outputs of the nodes in hidden layer number 3 is [0.868, 0.881]
The predicted values by the network for the given input are [0.8952, 0.8222, 0.8035]


In [28]:
my_network2 = initialize_network(5, 4, [2, 3, 2, 3], 3)
inputs = np.around(np.random.uniform(size=5), decimals=2)
predictions2 = forward_propagate(my_network2, inputs)
print('The predicted values by the network for the given input are {}'.format(predictions2))

The outputs of the nodes in hidden layer number 1 is [0.715, 0.6868]
The outputs of the nodes in hidden layer number 2 is [0.744, 0.7558, 0.8279]
The outputs of the nodes in hidden layer number 3 is [0.8522, 0.8415]
The outputs of the nodes in hidden layer number 4 is [0.7697, 0.9011, 0.8661]
The predicted values by the network for the given input are [0.7913, 0.9422, 0.903]


In [29]:
my_network3 = initialize_network(5, 2, [2, 1], 3)
inputs = np.around(np.random.uniform(size=5), decimals=2)
predictions3 = forward_propagate(my_network3, inputs)
print('The predicted values by the network for the given input are {}'.format(predictions3))

The outputs of the nodes in hidden layer number 1 is [0.7867, 0.8099]
The outputs of the nodes in hidden layer number 2 is [0.7781]
The predicted values by the network for the given input are [0.6785, 0.6336, 0.7036]
